### ISSUE TITLE
Minor harmless bug, Apps menu

### ISSUE THREAD

**Issue by srikanthBezawada** [ntamas/cl1#6]
Once the app is uninstalled, the menu item wouldn't go from "Apps" menu unless Cytoscape is restarted

**Comment by ntamas** [comment]
Thanks for the bug report. I'm not developing the Cytoscape plugin actively any more due to lack of time (since I am not working in academia any more). If someone stumbles upon this bug report and wants to contribute a pull request: I think it would be an easy fix, one would simply have to move the addition of the "Apps" menu items from the constructor of the plugin to the method where the plugin gets activated, and add the corresponding method calls to remove the menu items to the method where the plugin gets deactivated.

**Comment by srikanthBezawada** [comment]
@ntamas , I've added the fix. 
To remove the menu item, we need the instance of CyAction class and so, updated code accordingly.

I really liked the design of classes in the app and will be using the same template for my Cytoscape apps :).

**Comment by maryyar** [comment]
hi all
i am MSC of computer.my thesis about overlapping cammunity in social network.i do java code and i want create java code and app to cytoscape.how can i create app in cytoscap?help me please.thanks

**Comment by srikanthBezawada** [comment]
@maryyar  Here you go http://wiki.cytoscape.org/Cytoscape_3/AppDeveloper/Cytoscape_App_Ladder
 and have a look at existing app repositories to get started.

**Comment by srikanthBezawada** [comment]
@ntamas , Closing this as it is more of a very minor design issue and looks like sometimes apps get uninstalled completely only after restart.
